### ISSUE TITLE
`exercism-submit`  doesn't work when current work directory isn't problem's root dir

### ISSUE THREAD

**Issue by eval-exec** [anonimitoraf/exercism.el#4]
For example, there is a exercism problem whose file tree is:
```
├── HELP.md
├── README.md
├── src
    └── hello_world.clj

```

I open `src/hello_world.clj` in a buffer, and M-x `exercism-submit` will report `[exercism] submit: Error: no files to submit`, I have to execute `exercism-submit` in the problem's root directory to submit successfully.

**Comment by anonimitoraf** [comment]
Ah interesting. I'll see what I can do

**Comment by anonimitoraf** [comment]
Hey @eval-exec, mind trying the latest version?

For context, I've made the submit function explicitly specify the solution files (specified within the exercise's `config.json`)

**Comment by eval-exec** [comment]
> Hey @eval-exec, mind trying the latest version?
> 
> For context, I've made the submit function explicitly specify the solution files (specified within the exercise's `config.json)

Thank you, I will test it later.
